name: Deploy to Firebase Hosting

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Use a pre-built bundle from the build directory
      # This assumes you've already built the project locally and committed the build folder
      - name: Check if build directory exists
        id: check_build
        run: |
          if [ -d "build" ]; then
            echo "Build directory exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Build directory does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      # Deploy to Firebase directly using the firebase-tools Docker image
      - name: Deploy to Firebase
        if: steps.check_build.outputs.exists == 'true'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      
      # Show error message if build directory doesn't exist
      - name: Build directory missing
        if: steps.check_build.outputs.exists == 'false'
        run: |
          echo "Error: Build directory not found!"
          echo "Please run 'npm run build' locally and commit the build directory before deploying."
          exit 1
